import type {
  WorkflowEdge,
  WorkflowNodeDefinition,
  WorkflowProfile,
} from './contracts.ts';

const allProfiles: WorkflowProfile[] = ['quick', 'balanced', 'full'];
const balancedAndFull: WorkflowProfile[] = ['balanced', 'full'];

export const DEFAULT_WORKFLOW_NODES: WorkflowNodeDefinition[] = [
  {
    id: 'product',
    label: 'مدير المنتج',
    description: 'تحويل الفكرة إلى نطاق واضح، مستخدمين مستهدفين، وحالات استخدام قابلة للتنفيذ.',
    artifact: '01-product-brief.md',
    kind: 'analysis',
    optional: false,
    enabled: true,
    maxRetries: 1,
    position: { x: 850, y: 0 },
    profiles: allProfiles,
  },
  {
    id: 'market',
    label: 'محلل الاحتياج',
    description: 'تحليل البدائل والفجوات والافتراضات التي تحتاج إلى تحقق دون اختلاق بيانات.',
    artifact: '02-opportunity.md',
    kind: 'analysis',
    optional: true,
    enabled: true,
    maxRetries: 1,
    position: { x: 430, y: 170 },
    profiles: balancedAndFull,
  },
  {
    id: 'ux',
    label: 'باحث تجربة المستخدم',
    description: 'بناء الرحلة والسيناريوهات والحالات الفارغة والخاطئة ومبادئ سهولة الاستخدام.',
    artifact: '03-user-flow.md',
    kind: 'analysis',
    optional: false,
    enabled: true,
    maxRetries: 1,
    position: { x: 850, y: 170 },
    profiles: allProfiles,
  },
  {
    id: 'design',
    label: 'مصمم المنتج',
    description: 'تحديد بنية الشاشات والمكونات ونظام بصري متجاوب ومناسب للجوال.',
    artifact: '04-design-spec.md',
    kind: 'implementation',
    optional: false,
    enabled: true,
    maxRetries: 1,
    position: { x: 720, y: 350 },
    profiles: balancedAndFull,
  },
  {
    id: 'architecture',
    label: 'مهندس الأنظمة',
    description: 'اختيار أبسط بنية موثوقة، تدفقات البيانات، الحدود، وخطة التطوير.',
    artifact: '05-architecture.md',
    kind: 'implementation',
    optional: false,
    enabled: true,
    maxRetries: 1,
    position: { x: 1120, y: 350 },
    profiles: allProfiles,
  },
  {
    id: 'data',
    label: 'مهندس البيانات',
    description: 'تصميم نماذج البيانات والاستمرارية والهجرات والحالات المتعارضة.',
    artifact: '06-data-model.md',
    kind: 'implementation',
    optional: true,
    enabled: true,
    maxRetries: 1,
    position: { x: 1220, y: 540 },
    profiles: ['full'],
  },
  {
    id: 'api',
    label: 'مصمم الواجهات البرمجية',
    description: 'تحديد العقود والطلبات والاستجابات والأخطاء والإلغاء والاستعادة.',
    artifact: '07-api-contracts.md',
    kind: 'implementation',
    optional: false,
    enabled: true,
    maxRetries: 1,
    position: { x: 970, y: 540 },
    profiles: balancedAndFull,
  },
  {
    id: 'ai',
    label: 'مهندس الذكاء الاصطناعي',
    description: 'تصميم الاستدعاءات والسياق والتحقق من المخرجات والاستخدام الفعلي للنماذج.',
    artifact: '08-ai-plan.md',
    kind: 'implementation',
    optional: true,
    enabled: true,
    maxRetries: 1,
    position: { x: 1470, y: 540 },
    profiles: balancedAndFull,
  },
  {
    id: 'frontend',
    label: 'قائد الواجهة',
    description: 'خطة مكونات الواجهة والحالة والاستجابة والوصول والأداء.',
    artifact: '09-frontend-plan.md',
    kind: 'implementation',
    optional: false,
    enabled: true,
    maxRetries: 1,
    position: { x: 700, y: 730 },
    profiles: allProfiles,
  },
  {
    id: 'backend',
    label: 'قائد المنطق الخلفي',
    description: 'خطة التنفيذ الخلفي، إدارة المهام، الأخطاء، والمراقبة الوظيفية.',
    artifact: '10-backend-plan.md',
    kind: 'implementation',
    optional: false,
    enabled: true,
    maxRetries: 1,
    position: { x: 1210, y: 730 },
    profiles: ['full'],
  },
  {
    id: 'quality',
    label: 'مراجع الجودة',
    description: 'اختبار الاتساق وقابلية التنفيذ والحالات الطرفية ووضع بوابة جودة صريحة.',
    artifact: '11-quality-gate.md',
    kind: 'quality',
    optional: false,
    enabled: true,
    maxRetries: 1,
    position: { x: 930, y: 920 },
    profiles: balancedAndFull,
  },
  {
    id: 'final',
    label: 'المجمّع النهائي',
    description: 'إنتاج برومبت واحد متماسك وقابل للنسخ دون تكرار أو تضارب.',
    artifact: '12-final-prompt.md',
    kind: 'final',
    optional: false,
    enabled: true,
    maxRetries: 1,
    position: { x: 930, y: 1110 },
    profiles: allProfiles,
  },
];

export const DEFAULT_WORKFLOW_EDGES: WorkflowEdge[] = [
  { id: 'product-market', source: 'product', target: 'market' },
  { id: 'product-ux', source: 'product', target: 'ux' },
  { id: 'ux-design', source: 'ux', target: 'design' },
  { id: 'product-architecture', source: 'product', target: 'architecture' },
  { id: 'architecture-data', source: 'architecture', target: 'data' },
  { id: 'architecture-api', source: 'architecture', target: 'api' },
  { id: 'architecture-ai', source: 'architecture', target: 'ai' },
  { id: 'ux-frontend', source: 'ux', target: 'frontend' },
  { id: 'design-frontend', source: 'design', target: 'frontend' },
  { id: 'architecture-frontend', source: 'architecture', target: 'frontend' },
  { id: 'data-backend', source: 'data', target: 'backend' },
  { id: 'api-backend', source: 'api', target: 'backend' },
  { id: 'ai-backend', source: 'ai', target: 'backend' },
  { id: 'frontend-quality', source: 'frontend', target: 'quality' },
  { id: 'backend-quality', source: 'backend', target: 'quality' },
  { id: 'market-final', source: 'market', target: 'final' },
  { id: 'design-final', source: 'design', target: 'final' },
  { id: 'architecture-final', source: 'architecture', target: 'final' },
  { id: 'data-final', source: 'data', target: 'final' },
  { id: 'api-final', source: 'api', target: 'final' },
  { id: 'ai-final', source: 'ai', target: 'final' },
  { id: 'frontend-final', source: 'frontend', target: 'final' },
  { id: 'backend-final', source: 'backend', target: 'final' },
  { id: 'quality-final', source: 'quality', target: 'final' },
];

export function workflowForProfile(
  nodes: WorkflowNodeDefinition[],
  edges: WorkflowEdge[],
  profile: WorkflowProfile,
): { nodes: WorkflowNodeDefinition[]; edges: WorkflowEdge[] } {
  const selectedNodes = nodes
    .filter((node) => node.enabled && (!node.profiles || node.profiles.includes(profile)))
    .map((node) => ({ ...node, position: { ...node.position } }));
  const ids = new Set(selectedNodes.map((node) => node.id));
  const selectedEdges = edges.filter(
    (edge) => ids.has(edge.source) && ids.has(edge.target),
  );
  return { nodes: selectedNodes, edges: selectedEdges };
}

export const PROFILE_META: Record<
  WorkflowProfile,
  { label: string; description: string; concurrency: number; contextBudget: number }
> = {
  quick: {
    label: 'سريع',
    description: 'أقل عدد من الاستدعاءات لبلورة الفكرة بسرعة.',
    concurrency: 2,
    contextBudget: 8_000,
  },
  balanced: {
    label: 'متوازن',
    description: 'تفاصيل قوية وتكلفة معقولة لمعظم المشاريع.',
    concurrency: 3,
    contextBudget: 18_000,
  },
  full: {
    label: 'شامل',
    description: 'أقصى عمق للمشاريع المعقدة مع تدقيق جودة كامل.',
    concurrency: 4,
    contextBudget: 32_000,
  },
};
